#!/usr/bin/env bash
#Telling the story of passw

while IFS=: read -r username password userid groupid idinfo homedir cmdshell
do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $idinfo"
done < /etc/passwd
